Repository ChainSafe/erigon, pull requests merged in 2023-01, with the labels that each got.

#1 Feat/dev guide
  README.fh.md
  README.md
Labels: Priority: P2, Type: Documentation

#9 firehose context
  firehose/context.go
  firehose/context_test.go
  firehose/globals.go
  firehose/printer.go
  firehose/types.go
  firehose/validation.go
  firehose/validation_test.go
  go.mod
  go.sum
Labels: Priority: P1

#10 Feat/core state logs
  core/state/database_test.go
  core/state/intra_block_state.go
  core/state/intra_block_state_test.go
  core/state/state_object.go
  core/state/state_test.go
Labels: Priority: P1

#17 Firehose flag setup
  params/version.go
  turbo/app/make_app.go
  turbo/app/snapshots.go
  turbo/debug/flags.go
Labels: Priority: P1

#18 Added firehose context to core/vm
  core/vm/analysis_test.go
  core/vm/contract.go
  core/vm/contracts.go
  core/vm/contracts_test.go
  core/vm/cvm.go
  core/vm/evm.go
  core/vm/evm_test.go
  core/vm/evmtypes/evmtypes.go
  core/vm/gas_table_test.go
  core/vm/instructions.go
  core/vm/instructions_test.go
  core/vm/interface.go
  core/vm/interpreter.go
  core/vm/mock_vm.go
  core/vm/opcodes.go
  core/vm/operations_acl.go
  core/vm/runtime/env.go
  core/vm/runtime/runtime.go
  core/vm/runtime/runtime_test.go
Labels: Priority: P1

#19 Feat/core
  consensus/parlia/parlia.go
  core/blockchain.go
  core/bor_fee_log.go
  core/chain_makers.go
  core/evm.go
  core/genesis.go
  core/state_processor.go
  core/state_transition.go
  core/systemcontracts/upgrade.go
  core/vm/cvm_adapter.go
  firehose/context.go
Labels: Priority: P1, Status: Review Needed

#26 modules fixes
  accounts/abi/bind/backends/simulated.go
  cmd/evm/internal/t8ntool/execution.go
  cmd/evm/runner.go
  cmd/rpcdaemon/commands/eth_block.go
  cmd/rpcdaemon/commands/eth_call.go
  cmd/rpcdaemon/commands/eth_callMany.go
  cmd/rpcdaemon/commands/eth_receipts.go
  cmd/rpcdaemon/commands/otterscan_api.go
  cmd/rpcdaemon/commands/otterscan_generic_tracer.go
  cmd/rpcdaemon/commands/otterscan_search_trace.go
  cmd/rpcdaemon/commands/trace_adhoc.go
  cmd/rpcdaemon/commands/trace_filtering.go
  cmd/rpcdaemon/commands/tracing.go
  cmd/state/commands/erigon2.go
  cmd/state/commands/erigon4.go
  cmd/state/commands/history2.go
  cmd/state/commands/history22.go
  cmd/state/commands/opcode_tracer.go
  cmd/state/exec3/state.go
  cmd/state/exec3/state_recon.go
  core/genesis.go
  firehose/context_test.go
  firehose/validation.go
  tests/state_test_util.go
  turbo/adapter/ethapi/state_overrides.go
  turbo/app/make_app.go
  turbo/debug/flags.go
  turbo/transactions/call.go
  turbo/transactions/tracing.go
Labels: Priority: P1
